# https://minimo.netlify.com/docs/example-config-toml/

baseURL = "http://example.org/"
languageCode = "en-us"
title = "Open Practice Library"
theme = "minimo"
description = "Minimalist theme for Hugo"
