# https://gohugo.io/getting-started/configuration/
# https://github.com/MunifTanjim/minimo/blob/master/exampleSite/config.toml

baseURL = "https://openpracticelibrary.com/"
languageCode = "en-us"
title = "Open Practice Library"
theme = "casper"

googleAnalytics = "UA-111461618-1"

[params]
paginatedsections = ["practices"]
logo = "images/avatars/chameleon.png"
description = "Practices that empower teams to collaborate and deliver iteratively"
customFooterPartial = "netlify.html"

[params.assets]
customCSS = ["css/custom.css"]

[permalinks]
page = "/:slug/"

[[menu.main]]
  name = "GitHub"
  weight = 2
  identifier = "GitHub"
  url = "https://github.com/openpracticelibrary/openpracticelibrary"

[[menu.main]]
  name = "Gitter"
  weight = 1
  identifier = "Gitter"
  url = "https://gitter.im/openpracticelibrary/"