# https://gohugo.io/getting-started/configuration/
# https://github.com/MunifTanjim/minimo/blob/master/exampleSite/config.toml

baseURL = "/"
languageCode = "en-us"
title = "Open Practice Library"
theme = "minimo"


[permalinks]
page = "/:slug/"
