# https://gohugo.io/getting-started/configuration/
# https://github.com/MunifTanjim/minimo/blob/master/exampleSite/config.toml

baseURL = "https://openpracticelibrary.com/"
languageCode = "en-us"
title = "Open Practice Library"
theme = "casper"
# Why "docs" and not "public"? https://git.io/vXzj6
publishDir = "docs"
googleAnalytics = "UA-111461618-1"

[params]
paginatedsections = ["practices"]
logo = "images/avatars/chameleon.png"
description = "Practies that empower teams to collaborate and deliver iteratively"
customFooterPartial = "netlify.html"

[params.assets]
customCSS = ["css/custom.css"]

[permalinks]
page = "/:slug/"
